package com.ayproductions.appinventor.extensions.arithmetic.geometry.perimeterandarea.perimetercalculator;

import android.app.Activity;
import android.content.Context;
import com.google.appinventor.components.annotations.*;
import com.google.appinventor.components.common.ComponentCategory;
import com.google.appinventor.components.runtime.AndroidNonvisibleComponent;
import com.google.appinventor.components.runtime.ComponentContainer;
import com.google.appinventor.components.runtime.EventDispatcher;

@DesignerComponent(
        version = 1,
        description = "Perimeter Calculator",
        category = ComponentCategory.EXTENSION,
        nonVisible = true,
        iconName = "")

@SimpleObject(external = true)
//Libraries
@UsesLibraries(libraries = "")
//Permissions
@UsesPermissions(permissionNames = "")

public class PerimeterCalculator extends AndroidNonvisibleComponent {

    //Activity and Context
    private Context context;
    private Activity activity;

    public PerimeterCalculator(ComponentContainer container){
        super(container.$form());
        this.activity = container.$context();
        this.context = container.$context();
    }

    @SimpleFunction(description = "Sample Function Generated by Niotron")
    public Object CalculatePerimeterOfSquare(double side, String unit){
        return 4 * side + unit;
    }

    @SimpleFunction(description = "Sample Function Generated by Niotron")
    public Object CalculatePerimeterOfTriangle(double side1, double side2, double side3, String unit){
        return side1 + side2 + side3 + unit;
    }

    @SimpleFunction(description = "Sample Function Generated by Niotron")
    public Object CalculatePerimeterOfRectangle(double length, double breadth, String unit){
        return (length + breadth) * 2 + unit;
    }

    @SimpleFunction(description = "Sample Function Generated by Niotron")
    public Object CalculateLengthOfEachSideOfSquare(double perimeter, String unit){
        return perimeter / 4 + unit;
    }

    @SimpleProperty(description = "Sample Function Generated by Niotron")
    public Object UnitKilometre(){
        return "km";
    }

    @SimpleProperty(description = "Sample Function Generated by Niotron")
    public Object UnitHectometre(){
        return "hm";
    }

    @SimpleProperty(description = "Sample Function Generated by Niotron")
    public Object UnitDecametre(){
        return "dam";
    }

    @SimpleProperty(description = "Sample Function Generated by Niotron")
    public Object UnitMetre(){
        return "m";
    }

    @SimpleProperty(description = "Sample Function Generated by Niotron")
    public Object UnitDecimetre(){
        return "dm";
    }

    @SimpleProperty(description = "Sample Function Generated by Niotron")
    public Object UnitCentimetre(){
        return "cm";
    }

    @SimpleProperty(description = "Sample Function Generated by Niotron")
    public Object UnitMillimetre(){
        return "mm";
    }
}
